### ISSUE TITLE
How to use Lib.Net.Http.WebPush with ng build --prod and dist/ngsw-worker.js

### ISSUE THREAD

**Issue by toddtsic** [tpeczek/Lib.Net.Http.WebPush#10]
I have tested with Demo.AspNetCore.PushNotifications sample (extremely helpful for this topic and for good programming practice/examples -- thank you!)

There I notice the service worker is named "push-service-worker.js" and handles inbound messages on the client app with:
```
const pushNotificationTitle = 'Demo.AspNetCore.PushNotifications';

self.addEventListener('push', function (event) {
    event.waitUntil(self.registration.showNotification(pushNotificationTitle, {
        body: event.data.text(),
        icon: '/images/push-notification-icon.png'
    }));
});

self.addEventListener('notificationclick', function (event) {
    event.notification.close();
});
```
The app I'm building now is pure angular and I'm using the latest angular-cli:
```
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@angular/cdk                      7.0.2
@angular/cli                      7.1.4
@angular/material                 7.0.2
@angular/pwa                      0.12.2
@angular/service-worker           7.2.0
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
```

In the angular-cli app:

`ng build --prod` produces in `dist` directory a service worker named: ` ngsw-worker.js`

there, inbound messages are handled with code (automatically generated by `ng build`) with:
```
        onPush(msg) {
            // Push notifications without data have no effect.
            if (!msg.data) {
                return;
            }
            // Handle the push and keep the SW alive until it's handled.
            msg.waitUntil(this.handlePush(msg.data.json()));
        }

```
Sending a push notification from the server using:
```
public async Task SendNotificationAsync(PushSubscription subscription, PushMessage message, CancellationToken cancellationToken)
        {
            try
            {
                await _pushClient.RequestPushMessageDeliveryAsync(subscription, message, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger?.LogError(ex, "Failed requesting push message delivery to {0}.", subscription.Endpoint);
            }
        }
```
and with a PushMessage being defined as:
```
#region Assembly Lib.Net.Http.WebPush, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null
// C:\Users\tgree\.nuget\packages\lib.net.http.webpush\1.5.0\lib\netstandard2.0\Lib.Net.Http.WebPush.dll
#endregion

namespace Lib.Net.Http.WebPush
{
    //
    // Summary:
    //     Class representing a push message.
    public class PushMessage
    {
        //
        // Summary:
        //     Creates new instance of Lib.Net.Http.WebPush.PushMessage class.
        //
        // Parameters:
        //   content:
        //     The content.
        public PushMessage(string content);

        //
        // Summary:
        //     Gets or sets the topic (used to correlate messages sent to the same subscription).
        public string Topic { get; set; }
        //
        // Summary:
        //     Gets or sets the content.
        public string Content { get; set; }
        //
        // Summary:
        //     Gets or sets the time (in seconds) for which the message should be retained by
        //     push service.
        public int? TimeToLive { get; set; }
        //
        // Summary:
        //     Gets or sets the message urgency.
        public PushMessageUrgency Urgency { get; set; }
    }
}

```
the service worker line in `ngsw-worker.js`:

`msg.waitUntil(this.handlePush(msg.data.json()));`

fails with:

`Uncaught SyntaxError: Unexpected token T in JSON at position 0`

I can manually edit the `ngsw-worker.js`, swapping in the `push-service-worker.js` inbound handler from the Demo.AspNetCore.PushNotifications example to:
```
        // onPush(msg) {
        //     // Push notifications without data have no effect.
        //     if (!msg.data) {
        //         return;
        //     }
        //     // Handle the push and keep the SW alive until it's handled.
        //     msg.waitUntil(this.handlePush(msg.data.json()));
        // }
        onPush(event) {
            event.waitUntil(self.registration.showNotification('SOME TITLE HERE', {
                body: event.data.text(),
                icon: '/images/push-notification-icon.png'
            }));
        }

```
and the push succeeds.

Next I reviewed an Angular University example of push notifications which uses a `ng build` as server (so javascript server not Asp.NetCore), and uses `web-push": "^3.2.5` to process push notifications.  There the message is constructed with:
```
    const notificationPayload = {
        "notification": {
            "title": "Angular News",
            "body": "Newsletter Available!",
            "icon": "assets/main-page-logo-small-hat.png",
            "vibrate": [100, 50, 100],
            "data": {
                "dateOfArrival": Date.now(),
                "primaryKey": 1
            },
            "actions": [{
                "action": "explore",
                "title": "Go to the site"
            }]
        }
    };
```

This works fine with the default `dist/ngsw-worker.js` produced by `ng build --prod`

So I'm left with wondering about how to incorporate `Lib.Net.Http.Web` push with default produced `ng build --prod dist/ngsw-worker.js`

I could easily be missing something and there is currently a way to send a message with the data section (required by dist/ngsw-worker.js) but I don't see how given the current definition of a `PushMessage` ...

Any help here would be greatly appreciated.

Thanks,

Todd

**Comment by tpeczek** [comment]
You are on the right track, just few last steps missing.

Take a look at this call from Angular University example:

```js
webpush.sendNotification(sub, JSON.stringify(notificationPayload))
```

The second parameter of this call is represented through `PushMessage.Content` in `Lib.Net.Http.WebPush`. The `notificationPayload` is a higher layer object specific to Angular and you need to recreate it in C#, something like this:

```cs
public class AngularNotification
{
	public class AngularNotificationAction
	{
		public string Action { get; }

		public string Title { get; }

		public AngularNotificationAction(string action, string title)
		{
			Action = action;
			Title = title;
		}
	}

	private const string WRAPPER_START = "{\"notification\":";
	private const string WRAPPER_END = "}";

	private static readonly JsonSerializerSettings _jsonSerializerSettings = new JsonSerializerSettings
	{
		ContractResolver = new CamelCasePropertyNamesContractResolver()
	};

	public string Title { get; set; }

	public string Body { get; set; }

	public string Icon { get; set; }

	public IList<int> Vibrate { get; set; }

	public IDictionary<string, object> Data { get; set; }

	public IList<AngularNotificationAction> Actions { get; set; }

	public PushMessage ToPushMessage(string topic = null, int? timeToLive = null, PushMessageUrgency urgency = PushMessageUrgency.Normal)
	{
		return new PushMessage(WRAPPER_START + JsonConvert.SerializeObject(this, _jsonSerializerSettings) + WRAPPER_END)
		{
			Topic = topic,
			TimeToLive = timeToLive,
			Urgency = urgency
		};
	}
}
```

This will allow you to do something like this:

```cs
AngularNotification notificationPayload = new AngularNotification
{
	Title = "Angular News",
	Body = "Newsletter Available!",
	Icon = "assets/main-page-logo-small-hat.png",
	Vibrate = new List<int> { 100, 50, 100 },
	Data = new Dictionary<string, object>
	{
		{ "DateOfArrival", DateTime.Now },
		{ "PrimaryKey", 1 }
	},
	Actions = new List<AngularNotification.AngularNotificationAction>
	{
		new AngularNotification.AngularNotificationAction("explore", "Go to the site")
	}
};

await _pushClient.RequestPushMessageDeliveryAsync(subscription, notificationPayload.ToPushMessage());
```

Few remarks:
- This code is not tested, I wrote it based on reading the sample and documentation. Something might be wrong.
- This code can be written better, consider it more as a quick sample.

**Comment by toddtsic** [comment]
Tomasz,

Thanks so much for the rapid, and thorough response.

Here's what I tried (my project uses Demo.AspNetCore.PushNotifications as template)

- In the `.Services.Abstractions` project I added the `AngularNotification class`

- In the `.Services.PushService` project `SendNotificationAsync` method I changed to:

```
public async Task SendNotificationAsync(PushSubscription subscription, PushMessage message, CancellationToken cancellationToken)
        {
            try
            {
                AngularNotification notificationPayload = new AngularNotification
                {
                    Title = "Angular News",
                    Body = "Newsletter Available!",
                    Icon = "assets/main-page-logo-small-hat.png",
                    Vibrate = new List<int> { 100, 50, 100 },
                    Data = new Dictionary<string, object>
                    {
                        { "DateOfArrival", DateTime.Now },
                        { "PrimaryKey", 1 }
                    },
                    Actions = new List<AngularNotification.AngularNotificationAction>
                    {
                        new AngularNotification.AngularNotificationAction("explore", "Go to the site")
                    }
                };

                await _pushClient.RequestPushMessageDeliveryAsync(subscription, notificationPayload.ToPushMessage());
                //await _pushClient.RequestPushMessageDeliveryAsync(subscription, message, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger?.LogError(ex, "Failed requesting push message delivery to {0}.", subscription.Endpoint);
            }
        }
```

This takes your recommendation (which I can see isolates the problem, removing all issues of the request, and simply tries to send a message (still capturing and utilizing the subscription details))

When I  debug and analyze output of `notificationPayload.ToPushMessage()`

I get:

```
{
	"notification":{
		"title":"Angular News",
		"body":"Newsletter Available!",
		"icon":"assets/main-page-logo-small-hat.png",
		"vibrate":[100,50,100],
		"data":{
			"dateOfArrival":"2019-01-20T17:34:45.8912707-07:00",
			"primaryKey":1
		},
		"actions":[{
			"action":"explore",
			"title":"Go to the site"
		}]
	}
}
```
which appear identical to (copy and pasted from Angular University example, `send-newletter.route.ts'

```
const notificationPayload = {
        "notification": {
            "title": "Angular News",
            "body": "Newsletter Available!",
            "icon": "assets/main-page-logo-small-hat.png",
            "vibrate": [100, 50, 100],
            "data": {
                "dateOfArrival": Date.now(),
                "primaryKey": 1
            },
            "actions": [{
                "action": "explore",
                "title": "Go to the site"
            }]
        }
    };
```
so that seems fine (I assumed your `_pushClient.RequestPushMessageDeliveryAsync` required message to be of type `PushMessage`, expected a compiler error, but no, compiled and runs fine.

then run code and I get:

```
[17:40:41 Error] PushService.Abstractions.PushService.PushServicePushNotificationService
Failed requesting push message delivery to https://fcm.googleapis.com/fcm/send/erVkqgLz_gU:APA91bHyFptJgc7fLJhEFQkCs9rjMfuxz8H1RyKb5otF1jPX-IwCtis82uu9tBe7d48VWkTMkaMvj42FWu4R7lYfi1B-8YQ5ovr47ppxDH_Gykyz_kXbD4PtbLn4UxE2fl9tGUHpUNCu.
Lib.Net.Http.WebPush.PushServiceClientException: NotRegistered
   at Lib.Net.Http.WebPush.PushServiceClient.HandlePushMessageDeliveryRequestResponse(HttpResponseMessage pushMessageDeliveryRequestResponse)
   at Lib.Net.Http.WebPush.PushServiceClient.RequestPushMessageDeliveryAsync(PushSubscription subscription, PushMessage message, VapidAuthentication authentication, VapidAuthenticationScheme authenticationScheme, CancellationToken cancellationToken)
   at PushService.Abstractions.PushService.PushServicePushNotificationService.SendNotificationAsync(PushSubscription subscription, PushMessage message, CancellationToken cancellationToken) in E:\Projects-STS\TSIC\PushService.PushService\PushServicePushNotificationService.cs:line 60
```

I'm researching that currently (I'm updating here in case it would be useful for you or others...)

Todd

**Comment by tpeczek** [comment]
The `PushServiceClientException` represents an erroneous response from Push Service. The error would suggest that subscription you have stored locally is not known to the Push Service (either it has been removed through client side code but not removed from your database or it has expired on the Push Service).

In general in such case the subscription should be removed (in fact I'm planning to add suport for that in demo project tpeczek/Demo.AspNetCore.PushNotifications#9) and new made from the client side. This will prevent situation which might be happening right now - your database keeps old and new subscription and you're getting exception for the old one.

**Comment by toddtsic** [comment]
Tomasz,

Got it, and I'm up and working, thanks much.

I'm still catching up on push notifications in general...

I'm wondering about the distinction "AngularNotification" above.  I know from an Ionic app I wrote previously, that the payloads for iOS and Android do differ, but I was thinking the web push was more a function of the browser and not the os.

I'm writing this Angular app as a progressive app.  Will my server need to distinguish the target types <web:Windows10, webiOS, mobile:Android, mobile:iOS> and package notification objects specific to each, or is their any hope of using a single notification object?

Thanks,

Todd

**Comment by tpeczek** [comment]
From Web Push perspective, the data is only a string (as `PushMessage.Content` signifies). Any specific format is considered custom and usually belongs to specific framework. So, as long as your PWA is Angular based on all platforms, I believe you should be good with single object.

**Comment by toddtsic** [comment]
wow, that has huge implications, thanks much, continuing to pour over your code and learning tons.

fyi, just tried sending you some "coffee", link produces 2 cc txs  (no double click) and is rejected as fraud.

**Comment by tpeczek** [comment]
No problem.

And regarding those coffees, that's weird. Here is a direct link: https://www.buymeacoffee.com/tpeczek. If you have problems with it, well bad luck on me.
