### ISSUE TITLE
Allow arbitrary binary data as PushMessage content

### ISSUE THREAD

**Issue by Peter-Juhasz** [tpeczek/Lib.Net.Http.WebPush#11]

**Comment by tpeczek** [comment]
I'll need to think about nicely structuring `PushMessage` for this.

**Comment by tpeczek** [comment]
I guess the most powerful way is to add another constructor which allows providing `HttpContent` (this will allow for any arbitrary data).

```cs
public class PushMessage
{
    public PushMessage(HttpContent content)
    {
        ...
    }
}
```

This will make `Content` property a little bit awkward as it will have to throw when that constructor will be used, but I want to keep it to maintain backward compatibility.

@Peter-Juhasz Would this approach work for your use case?
