### ISSUE TITLE
Request/response messages are not disposed

### ISSUE THREAD

**Issue by Peter-Juhasz** [tpeczek/Lib.Net.Http.WebPush#12]
This is far the best implementation available, so thank you, really appreciate your work. :)

Looking at the implementation of PushServiceClient, it seems like HttpRequestMessage and HttpResponseMessage instances are not disposed after use which may lead to a memory leak.

**Comment by tpeczek** [comment]
You are welcome and thank you for kind words.

In general calling `Dispose` shouldn't be important here. The only useful thing disposing a request or response does is calling `Dispose` on their content on some platforms (on .NET Core not even that happens). The only content type that needs disposing is `StreamContent` which is not used here.

That said, your issue made me consider adding it in case implementation changes in future or on a new platform. If I'm able to add it without to much clutter in the code, I'll do it.
