### ISSUE TITLE
Client Error Messages are hidden

### ISSUE THREAD

**Issue by pfegerpaul** [tpeczek/Lib.Net.Http.WebPush#16]
Client notification failures can have detailed information in the HTTP Response.
    
    The HTTP Code can't help identify the error.
    
    The fix includes the HTTP Response in the Exception. (see files)
    [Fix.zip]([https://github.com/tpeczek/Lib.Net.Http.WebPush/files/4262703/Fix.zip]

    
    E.g. See [https://autopush.readthedocs.io/en/latest/http.html#errors](Mozilla Push Notification Errors)

**Comment by tpeczek** [comment]
Hi @pfegerpaul 

I will be happy to take a look at this and hopefully get this in. I'm traveling this week, so this will not happen earlier than next weekend.
