### ISSUE TITLE
Enhancement: Provide ability to set AutoRetryAfter & DefaultTimeToLive via PushServiceAttribute

### ISSUE THREAD

**Issue by techfg** [tpeczek/Lib.Net.Http.WebPush#17]
Currently when using the PushService attribute binding in an azure function, there is no method to set the AutoRetryAfter or DefaultTimeToLive properties of the PushClient.

Would be helpful to be able to control these from the binding directly as well as provide a "MaxRetries" property on the binding and inside PushClient.

**Comment by techfg** [comment]
@tpeczek - Thought it made sense to have a discussion on approach here before working on final implementation since this one could be done a few different ways.

With the proposed MaxRetries concept, I think if this was being developed from scratch, we could simply have a MaxRetries integer that is -1 (unlimited), 0 (off/no retries), > 0 (user specified).  However, for backwards compat, I think we need to maintain the AutoRetryAfter boolean.

Given that, here's my thoughts.  Let me know yours when you get a chance:

1) AutoRetryAfter - Maintained as-is (default true).  Controls whether or not retries are attempted for 429 return status
2) MaxRetries - 0 (unlimited), > 0 (user specified limit).  If AutoRetryAfter == false, MaxRetries is ignored.  Default would be 0.
3) DefaultTimeToLive - Maintained as-is

**Comment by tpeczek** [comment]
@techfg I'm in favor of adding `MaxRetries` which will be a limit of retries if it has a positive value and `AutoRetryAfter` is set to `true`.

**Comment by techfg** [comment]
@techfg - Thanks, sounds like a plan.  I'll try to get to it soon and submit a PR.
