### ISSUE TITLE
Investigate dropping BouncyCastle dependency

### ISSUE THREAD

**Issue by tpeczek** [tpeczek/Lib.Net.Http.WebPush#4]
Currently this library has dependency on two different BouncyCastle builds. It would be perfect to drop the BouncyCastle dependency, but it requires new APIs in CoreFX/NetFX.

[DEPENDS ON] ~~dotnet/runtime#17152~~
[DEPENDS ON] ~~dotnet/runtime#22610~~
[DEPENDS ON] ~~tpeczek/Lib.Net.Http.EncryptedContentEncoding#4~~

**Comment by clairernovotny** [comment]
Hi,

I recommend you use my Portable.BouncyCastle package. It's the official one and the PR with its changes will be brought into BC once the maintainers are ready with their next release.

It supports all platforms and is a drop-in replacement.

**Comment by tpeczek** [comment]
Hi @onovotny,

Thank you for the suggestion. Indeed it seems to be a well maintained and popular version (especially in comparison to BouncyCastle.CoreClr). I think I'll first give it a go in [Lib.Net.Http.EncryptedContentEncoding](https://github.com/tpeczek/Lib.Net.Http.EncryptedContentEncoding) and then here.

**Comment by tpeczek** [comment]
Currently this library depends on Portable.BouncyCastle. In future it might be still worth to consider dropping the BouncyCastle dependency in favour of native CoreFX/NetFX APIs.

**Comment by tuwrraphael** [comment]
As I mentioned in an [issue in web-push-libs/web-push-csharp](https://github.com/web-push-libs/web-push-csharp/issues/50#issuecomment-458745155) , the required aes-gcm cipher will be available in .net core3 (it is already included in the preview 1).

**Comment by tpeczek** [comment]
@tuwrraphael Yes. It's not enough to drop BouncyCastle entirely (ASN.1 reader/writer missing) but it should be enough to close tpeczek/Lib.Net.Http.EncryptedContentEncoding#4.
