### ISSUE TITLE
Microsoft Edge notifications don't work

### ISSUE THREAD

**Issue by andreiflaviusivan** [tpeczek/Lib.Net.Http.WebPush#6]
Hello,

Thanks for creating this library. It's really useful! I've encountered an issue with MS Edge, notifications work fine with Chrome and Firefox. When trying to send a notification to a MS edge channel, the request is not fine, I could see something like "Length required" in console.
```
Demo.AspNetCore.PushNotifications.Services.PushService.PushServicePushNotificationService[0]
Demo.AspNetCore.PushNotifications>       Failed requesting push message delivery to https://bl2p.notify.windows.com/w/?token=BQYAAAA96bglLC2PFjLB3zuUCX6BAIRtF0f2EVW1zDutn747tIl%2f83BBPoVI9GipwpOIY3im16yP5jdqtomfgkFHe%2fb313Jp9y%2b8qP79owrFivYNhF8kqVxBKGsscWVEwG2XQyQ0B1tFd5zSqJd9lTBOt93CMFzeJYzG3wUDmspqspeCbUzkr59pvGJfqRmVIhh1sn2FuzFTZI5hqTSSTI2SEZte8a95Xq%2bCp%2fcTqWUs8xnmZrqtig3Ucscj1bpqrw5TJMEV%2b30EV8WfkbHEGIAJEHr1N4fPt2Y1yHYAASFe1x%2bgEcPb3xTwp26Ny%2frUoPHjKyulcZygjU5ntND%2f0PbMJTuK.
Demo.AspNetCore.PushNotifications> Lib.Net.Http.WebPush.PushServiceClientException: Length Required
Demo.AspNetCore.PushNotifications>    at Lib.Net.Http.WebPush.PushServiceClient.HandlePushMessageDeliveryRequestResponse(HttpResponseMessage pushMessageDeliveryRequestResponse)
Demo.AspNetCore.PushNotifications>    at Lib.Net.Http.WebPush.PushServiceClient.RequestPushMessageDeliveryAsync(PushSubscription subscription, PushMessage message, VapidAuthentication authentication, VapidAuthenticationScheme authenticationScheme, CancellationToken cancellationToken)
Demo.AspNetCore.PushNotifications>    at Demo.AspNetCore.PushNotifications.Services.PushService.PushServicePushNotificationService.SendNotificationAsync(PushSubscription subscription, PushMessage message, CancellationToken cancellationToken) in C:\Users\wordbee\Documents\Workings\tmp\Demo.AspNetCore.PushNotifications-master\Demo.AspNetCore.PushNotifications.Services.PushService\PushServicePushNotificationService.cs:line 44
Demo.AspNetCore.PushNotifications> fail: Demo.AspNetCore.PushNotifications.Services.PushService.PushServicePushNotificationService[0]
```

I've managed to work around this by calling the ReadAsByteArrayAsync() in the push client:
```
private static HttpRequestMessage SetContent(HttpRequestMessage pushMessageDeliveryRequest, PushSubscription subscription, PushMessage message)
        {
            if (String.IsNullOrEmpty(message.Content))
            {
                pushMessageDeliveryRequest.Content = null;
            }
            else
            {
                AsymmetricCipherKeyPair applicationServerKeys = ECKeyHelper.GenerateAsymmetricCipherKeyPair();
                byte[] applicationServerPublicKey = ((ECPublicKeyParameters)applicationServerKeys.Public).Q.GetEncoded(false);

                pushMessageDeliveryRequest.Content = new Aes128GcmEncodedContent(
                    new StringContent(message.Content, Encoding.UTF8),
                    GetKeyingMaterial(subscription, applicationServerKeys.Private, applicationServerPublicKey),
                    applicationServerPublicKey,
                    CONTENT_RECORD_SIZE
                );

                pushMessageDeliveryRequest.Content.ReadAsByteArrayAsync().Wait();

                //pushMessageDeliveryRequest.Content.Headers.Add("Content-Length", message.Content.Length.ToString());
            }

            return pushMessageDeliveryRequest;
        }
```
Do you have any idea about what's happening?

Thanks,
Andrei

**Comment by tpeczek** [comment]
My blind guess would be that MS Edge requires Content-Length in push message delivery request, and `Aes128GcmEncodedContent` returns false from `TryComputeLength`. Not suprise there as computing length would require encrypting and buffereing the content. This is what you are doing by calling `ReadAsByteArrayAsync`.

I will investigate this. If you want to use your own version meantime, I would suggest usage of `LoadIntoBufferAsync` instead of `ReadAsByteArrayAsync` and changing that method to `async` so `await` can be used instead of `Wait`.

**Comment by andreiflaviusivan** [comment]
OK I understand the logic now. I'll use my version until you finish your investigation.

Cheers,
Andrei

**Comment by tpeczek** [comment]
@andreiflaviusivan did you use my demo application or do you have your own? I seem to have a problem with registering Service Worker in Edge. Also are you using WebPush or VAPID for authentication schema (`PushServiceClient.DefaultAuthenticationScheme` or equivalent parameter on `PushServiceClient.RequestPushMessageDeliveryAsync`)?

**Comment by andreiflaviusivan** [comment]
@tpeczek  I used the same application as here https://github.com/tpeczek/Demo.AspNetCore.PushNotifications

I didn't change the authentication scheme, I used the default one

**Comment by tpeczek** [comment]
@andreiflaviusivan I have just pushed Lib.Net.Http.WebPush 1.5.0 to NuGet which essentially bumps Lib.Net.Http.EncryptedContentEncoding dependency to 1.4.0. In Lib.Net.Http.EncryptedContentEncoding 1.4.0 I've added `TryComputeLenght` implementation which should work with type of content which is being used here. So it should resolve the issue and avoid performance penalty resulting from buffering.

I'm unable to fully test this, as something is wrong with MS Edge on my machine and attempt to install Service Worker always results in TypeError (not only in my application but in any application I've tried online). So I need to ask you to remove your workaround and test the new version so I can be sure that I can close this issue.

**Comment by andreiflaviusivan** [comment]
@tpeczek Many thanks, I'll do a try in an hour or so. Keep you posted ;)

**Comment by andreiflaviusivan** [comment]
Hey I've done some tests now and it seems just fine 👍 Thank you very much! I'm closing the issue

**Comment by tpeczek** [comment]
Great to hear! Thank you for bringing the issue up very clearly, helping me with testing and of course for the coffee :wink:

**Comment by seanyao1** [comment]
@tpeczek According HTTP 1.1 spec, Content-Length is required for non-empty request body (without chunking). In your case, is message.Content empty?

**Comment by tpeczek** [comment]
@seanyao1 The trick is the "without chunking" part. Under the hood the library must encrypt the content. In order to avoid buffering the encrypted version of content (and in some cases the original content as well, as it might be `StreamContent`) the library does it "in flight", which results in chunking. Right now the problem is solved as long as the original content length is known, in those cases the encrypted content length can be predicted without buffering. This means that in case of Edge you can't passed unbuffered `StreamContent` (or any other content implementation which returns `false` from `TryComputeLength`).
