### ISSUE TITLE
Using this library with UWP app "alternate channel"

### ISSUE THREAD

**Issue by nbevans** [tpeczek/Lib.Net.Http.WebPush#7]
Reference: https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/alternate-channel-vapid-webpush

We've made a UWP app which calls the `CreateRawPushNotificationChannelWithAlternateKeyForApplicationAsync` API. This returns a endpoint URL which contains a token in the query string of the URL. No `p256dh` or `auth` parameters are returned by this API.

I'm unclear now how to proceed because every WebPush library, including this one, seems to require as a minimum the `endpoint`, `p256dh` and `auth` to form a complete "push subscription".

The documentation on the MSDN there, as you can see, is extremely vague!

I have generated a VAPID public+private key pair and that part seems fine. I am passing in the public key part of this into that `CreateRawPushNotificationChannelWithAlternateKeyForApplicationAsync` function as the `appServerKey` parameter. But am now unclear what to do in order to get the `p256dh` and `auth` parts which appear to be essential.

Any ideas/tips would be greatly appreciated! Thank you.

**Comment by tpeczek** [comment]
Windows Push Notification Services (WNS) are vendor specific notifications (Android and iOS also have similar services), designed for native applications on given platform. They doesn't follow [Web Push Protocol](https://tools.ietf.org/html/rfc8030) (although there are various similarities. You need to use their specific protocol. I have never used the UWP push notifications and I don't know details of their protocol, but I would suspect that Microsoft delivers needed libraries.
