### ISSUE TITLE
Apply selected open-source library guidance

### ISSUE THREAD

**Issue by tpeczek** [tpeczek/Lib.Net.Http.WebPush#8]
Apply selected open-source library guidance:
- Add a target for `net461`
- Strong name the assembly
- Replace `PackageLicenseUrl` with `PackageLicenseExpression`

[DEPENDS ON] ~~tpeczek/Lib.Net.Http.EncryptedContentEncoding#8~~

<br /><hr />

Open-source library guidance: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/

**Comment by theLeftTenant** [comment]
I noticed that the strong naming issue was present in the other .Net WebPush-based libraries too, [for instance](https://github.com/web-push-libs/web-push-csharp/issues/30). Seems like strong naming would make it accessible in a lot more projects.

**Comment by tpeczek** [comment]
I'm hoping to get this done by Monday.

**Comment by theLeftTenant** [comment]
Great. Once you publish your changes to the NuGet package, I'll install and ensure the strong name stuff is resolved.

**Comment by tpeczek** [comment]
@theLeftTenant It's up on NuGet, you can test.

**Comment by theLeftTenant** [comment]
@tpeczek That did the trick!

**Comment by tpeczek** [comment]
Happy I could improve the experience for you :)
